version: '3'

services:
  app:
    image: kopiro/otto
    build: .
    environment:
      - DEV=1
    volumes:
      - ./cache:/app/cache
      - ./storage:/app/storage
      - ./tmp:/app/tmp
      - ./log:/app/log
      - ./keys:/app/keys
      - ./tmp-secret:/app/tmp-secret
      - ./config.json:/app/config.json
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./src:/app/src
    ports:
      - 8880:8880
      - 8881:8881
      - 8882:8882
